export const defaultTheme = {
    colors: {
        black: "#000000",
        white: "#ffffff",
        gray: "#f5f5f5",
        yellow: "#ffdf31",
        red: "#ff6666",
    },

    media: {
        desktop: "(min-width: 1440px)",
        tablet: "(min-width: 768px)",
        mobile: "(min-width: 375px)",
    },

    sizes: {
        borderRadius: "8px",
        cardPadding: "24px",
        cardTextFontSize: "18px",
        cardTextLineHeight: "23px",
        btnPadding: "12px 16px",
        defaultFontSize: "24px",
        defaultLineHeight: "31px",
        smallTextFontSize: "14px",
        footerTextLineHeight: "18px",
        smallTextLineHeight: "22px",
        popupSmallMargin: "24px",
        formBigMargin: "30px",
        formSmallMargin: "12px",
    },

    mobileSizes: {
        pageWidth: "375px",
        pagePadding: "15px",
        headerHeight: "78px",
        headerPadding: "24px",
        logoTextFontSize: "24px",
        logoTextLineHeight: "31px",
        mainTitleFontSize: "48px",
        mainTitleLineHeight: "44px",
        secondTitleFontSize: "24px",
        secondTitleLineheight: "31px",
        instagramBlockIndent: "12px",
        indent: "48px",
        cardWidth: "252px",
        cardHeight: "344px",
        mapheight: "600px",
        footerMainBlockHeight: "126px",
        popupBigMargin: "32px",
        stickyMenuTopIndent: "18px",
    },

    tabletSizes: {
        pageWidth: "768px",
        pagePadding: "39px",
        headerHeight: "111px",
        headerPadding: "32px",
        logoTextFontSize: "32px",
        logoTextLineHeight: "41px",
        phoneFontSize: "18px",
        phoneLineHeight: "23px",
        mainTitleFontSize: "72px",
        mainTitleLineHeight: "66px",
        secondTitleFontSize: "32px",
        secondTitleLineheight: "41px",
        instagramBlockIndent: "30px",
        indent: "72px",
        cardWidth: "300px",
        cardHeight: "410px",
        mapheight: "600px",
        footerMainBlockHeight: "89px",
        popupBigMargin: "48px",
    },

    desktopSizes: {
        pageWidth: "1440px",
        pagePadding: "165px",
        cardWidth: "350px",
        cardHeight: "482px",
        mapheight: "540px",
    },

    fonts: {
        family: '"Euclid Circular B", "Arial", sans-serif',
        regularWeight: "400",
        mediumWeight: "500",
    },
  };